### PR TITLE
Change ui for smaller device

### PR DESCRIPTION
**Pull request by madvier83**
Thanks for reading my pull request :)

### CODE REVIEW

**Comment by anurrags** [comment]
@madvier83 
1. Sync your project with the main repository
2. You have also changed the ui for desktop screen, which is not required (placing the rules at bottom)
3. Most of the areas in mobile view or vertical tablet view is empty.
4. Horizontal tablet view should have whole content without any scroll bar.

**Comment by anurrags** [comment]
For vertical view in tablet and mobile, it is still not responsive.
Screenshot 2022-10-03 at 08 04 24
Screenshot 2022-10-03 at 08 04 07

**Comment by madvier83** [comment]
its the problem with the browser mobile view (not updating the screen size), try resize it manually a little bit

**Comment by madvier83** [comment]
try using this extension to check 
https://chrome.google.com/webstore/detail/mobile-simulator-responsi/ckejmhbmlajgoklhgbapkiccekfoccmk/related

**Comment by anurrags** [comment]
@madvier83 Your work is very fine, just change the position of "rules" in mobile and tablet view to bottom as you did earlier, but not in desktop view.
I will merge it with hacktoberfest-accepted.
Screenshot 2022-10-03 at 08 23 46

**Comment by anurrags** [comment]
Check for the desktop version, part of the bottom two buttons are out of view area and is un-scrollable 
Screenshot 2022-10-03 at 10 05 52

**Pull request merged**
