### PR TITLE
[Updated] Enhanced the rule box closing

### PR DESCRIPTION
**Pull request by Rishabh044**
Updated the fix for Issue [#2](https://github.com/anurrags/Simon-game/issues/2)

### CODE REVIEW

**Comment by anurrags** [comment]
You have changed the UI more than required.
[Simons game](https://anurrags.github.io/Simon-game/) visit this link and see the UI of game, it should not change and webpage is responsive as well.
So you need not to change any responsiveness or positions of buttons. No UI change is needed. 
You just add the feature to close the Rules box by pressing escape or clicking anywhere outside the box.
So just do that much work and submit a PR request

**Comment by Rishabh044** [comment]
Ok sure

**Comment by anurrags** [comment]
Your branch have conflict with the main branch of my repository, so i can't directly merge it.
Solve that conflict first and then create a PR

**Comment by anurrags** [comment]
@Rishabh044 can you please do the below mentioned steps to resolve the conflict
Screenshot 2022-10-03 at 22 42 21

**Comment by Rishabh044** [comment]
Sure, I will do this by tommorow evening :'(

**Pull request closed without merging**
